### ISSUE TITLE
Pip install fails inside docker / No module named 'quant_linear_cuda'

### ISSUE THREAD

**Issue by aatkinson** [enyac-group/Quamba#7]
I am running `pip install` inside the docker you have provided and I get
```
      In file included from csrc/linear/quant_linear_fwd.cu:1:
      csrc/linear/quant_linear_fwd_kernel.cuh:13:10: fatal error: cute/tensor.hpp: No such file or directory
         13 | #include <cute/tensor.hpp>
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      In file included from csrc/linear/quant_linear_fwd.cu:1:
      csrc/linear/quant_linear_fwd_kernel.cuh:13:10: fatal error: cute/tensor.hpp: No such file or directory
         13 | #include <cute/tensor.hpp>
            |          ^~~~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 255
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
```

I did this since I can't run any of your `generate` examples since there is a missing module `` so I assume I must build and install this myself since it isn't in the docker image by default, that I can see.

```
Traceback (most recent call last):
  File "/code/generate.py", line 19, in <module>
    from quamba.real_quant.modelutils_mamba import quantize_blocks, run_calibration
  File "/code/quamba/real_quant/__init__.py", line 1, in <module>
    from .modelutils_mamba import quantize_model_mamba
  File "/code/quamba/real_quant/modelutils_mamba.py", line 13, in <module>
    from .qMambaLayer import QMamba, MambaSimple
  File "/code/quamba/real_quant/qMambaLayer.py", line 26, in <module>
    from .qLinearLayer import W8A8B8O8Linear, W8A8BF16OF16Linear, HadW8A8BF16OF16Linear, HadLinear
  File "/code/quamba/real_quant/qLinearLayer.py", line 4, in <module>
    import quant_linear_cuda
ModuleNotFoundError: No module named 'quant_linear_cuda'
```

Any help would be appreciated thank you.

**Comment by hychiang-git** [comment]
Please follow the installation steps before running our code in the docker. Our docker only contains the pure cuda environment. Thanks.

**Comment by hychiang-git** [comment]
I will close the issue. Welcome to reopen the issue if you cannot resolve it.
